### ISSUE TITLE
It was nice while it lasted!

### ISSUE THREAD

**Issue by njoyedevs** [lukas-reineke/indent-blankline.nvim#947] opened 2024-11-16 04:23 UTC
### Problem

I really liked your package.  Now it is broken due to the hooks.

### Steps to reproduce

nvim and then :Ex

### Expected behavior

It crashes nvim when i perform :Ex

### Neovim version (nvim -v)

10

**Comment by lukas-reineke** [comment] 2024-11-16 05:54
You will have to provide a bit more information for me to be able to help you.

Why do you think it has something to do with hooks? Hooks have not changed much in years.

Can you provide any error message, backtrace?

**Comment by njoyedevs** [comment] 2024-11-17 07:43
Sure thing.  I have tried a million versions of adding something in
after/plugin while using the most basic lazy.lua initialization.

Failed to source
`/home/njoye/.config/nvim/after/plugin/indent-blankline.lua`

vim/_editor.lua:0: /home/.config/nvim/init.lua..nvim_exec2() called at
/home/.config/nvim/init.lua:0../home/.config/nvim/after/plugin/indent-blankline.lua:
Vim(source):E5113: Error while calling lua chunk:
.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: type:
expected function: 0x7f392bafc9e0, got string (HIGHLIGHT_SETUP)
stack traceback:
[C]: in function 'error'
vim/shared.lua: in function 'validate'
.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: in function
'validate'
.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/hooks.lua:61: in function
'register'
....dotfiles/.config/nvim/after/plugin/indent-blankline.lua:14: in main
chunk
[C]: in function 'nvim_exec2'
vim/_editor.lua: in function 'cmd'
...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:506: in
function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:505>
[C]: in function 'xpcall'
.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:135: in
function 'try'
...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:505: in
function 'source'
...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:453: in
function 'source_runtime'
...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:150: in
function 'startup'
...njoye/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:112: in
function 'setup'
/home/njoye/.config/nvim/lua/thenickagen/lazy.lua:19: in main chunk
[C]: in function 'require'
/home/.config/nvim/lua/then/init.lua:3: in main chunk
[C]: in function 'require'
/home/.config/nvim/init.lua:1: in main chunk

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - ~/.config/nvim/lua/then/lazy.lua:19
  - ~/.config/nvim/lua/then/init.lua:3
  - ~/.dotfiles/.config/nvim/init.lua:1

**Comment by njoyedevs** [comment] 2024-11-17 07:47
Sure thing.  I have tried a million versions of adding something in
after/plugin while using the most basic lazy.lua initialization.

Failed to source `/home/.config/nvim/after/plugin/indent-blankline.lua`

vim/_editor.lua:0: /home/.config/nvim/init.lua..nvim_exec2() called at
/home/.config/nvim/init.lua:0../home/.config/nvim/after/plugin/indent-blankline.lua:
Vim(source):E5113: Error while calling lua chunk:
.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: type:
expected function: 0x7f392bafc9e0, got string (HIGHLIGHT_SETUP)
stack traceback:
[C]: in function 'error'
vim/shared.lua: in function 'validate'
.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: in function
'validate'
.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/hooks.lua:61: in function
'register'
....dotfiles/.config/nvim/after/plugin/indent-blankline.lua:14: in main
chunk
[C]: in function 'nvim_exec2'
vim/_editor.lua: in function 'cmd'
...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:506: in
function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:505>
[C]: in function 'xpcall'
.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:135: in
function 'try'
...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:505: in
function 'source'
...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:453: in
function 'source_runtime'
...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:150: in
function 'startup'
...njoye/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:112: in
function 'setup'
/home/.config/nvim/lua/then/lazy.lua:19: in main chunk
[C]: in function 'require'
/home/.config/nvim/lua/then/init.lua:3: in main chunk
[C]: in function 'require'
/home/.config/nvim/init.lua:1: in main chunk

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - ~/.config/nvim/lua/then/lazy.lua:19
  - ~/.config/nvim/lua/then/init.lua:3
  - ~/.dotfiles/.config/nvim/init.lua:1

**Comment by lukas-reineke** [comment] 2024-11-17 08:30
Your Neovim version is not 10.
This is a duplicate of #936. You are on an outdated nightly build.

Please update Neovim.

**Closed by lukas-reineke** 2024-11-17 08:30 UTC
Labels: bug

**Comment by njoyedevs** [comment] 2024-11-17 10:03
You rock :)!  Much appreciated. Great work!!!
