### ISSUE TITLE
Configuration of indent.char causes type validation error despite following documentation

### ISSUE THREAD

**Issue by camballe** [lukas-reineke/indent-blankline.nvim#948] opened 2024-11-18 12:27 UTC
### Problem

When attempting to configure the `indent.char` setting using the documented syntax, the plugin throws a type validation error. This occurs with both string and array table formats, despite the documentation indicating both should work.

Error message received:
Error detected while processing BufEnter Autocommands for "*":
Failed to run `config` for indent-blankline.nvim
.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: char: expected table: 0x7f3799752e38, got table (table: 0x7f37993cd628)

### Steps to reproduce

1. Install latest indent-blankline.nvim (v3.8.5)
2. Create a minimal configuration file with any of these attempts:

Attempt 1:
return {
    {
        "lukas-reineke/indent-blankline.nvim",
        main = "ibl",
        opts = {
            indent = { char = "┆" },
        },
    },
}

Attempt 2:
return {
    {
        "lukas-reineke/indent-blankline.nvim",
        main = "ibl",
        opts = {
            indent = { char = { "┆" } },
        },
    },
}

Attempt 3:
return {
    {
        "lukas-reineke/indent-blankline.nvim",
        main = "ibl",
        config = function()
            require("ibl").setup({
                indent = {
                    char = "┆",
                },
            })
        end,
    },
}

3. Start Neovim
4. Observe error message

Note: An empty configuration (opts = {}) works without error, but any attempt to configure indent.char fails.

### Expected behavior

Based on the documentation at `:help ibl.config.indent`, both string and string[] formats should be valid for the indent.char setting:

- {char}              (string|string[])
                     Character, or list of characters, that get used to
                     display the indentation guide

The configuration should accept either format and display the specified indentation character.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-989+g3f3e4837d5 Build type: Release LuaJIT 2.1.1727870382

**Comment by lukas-reineke** [comment] 2024-11-18 13:43
Duplicate of #936
Please make sure your Neovim version is up to date

**Closed by lukas-reineke** 2024-11-18 13:43 UTC
Labels: bug
