### ISSUE TITLE
04e44b0 breaks hooks.register() parameter validation

### ISSUE THREAD

**Issue by farces** [lukas-reineke/indent-blankline.nvim#945] opened 2024-11-12 07:48 UTC
### Problem

Since commit 04e44b0 indent-newline fails when registering a hook during setup, with the below error noting that validate wants the type parameter to be a function, when the function definition wants the type parameter to be a string:
```
Failed to run `config` for indent-blankline.nvim

.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: type: expected function: 0x7fb26c1b7e90, got string (HIGHLIGHT_SETUP)

# stacktrace:
  - vim/shared.lua:0 _in_ **validate**
  - /indent-blankline.nvim/lua/ibl/utils.lua:22 _in_ **validate**
  - /indent-blankline.nvim/lua/ibl/hooks.lua:61 _in_ **register**
  - ~/.config/nvim/lua/kickstart/plugins/indent_line.lua:41 _in_ **config**
```

The offending code in my lazy.nvim config for indent-newline is:
```lua
hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
      vim.api.nvim_set_hl(0, 'winter_blue', { fg = '#252535' })
    end)
```

Reverting to the commit immediately prior to this restores the behavior.

### Steps to reproduce

Using the below Lazy.nvim config for indent-newline:
```lua
-- indent-blankline

return {
  'lukas-reineke/indent-blankline.nvim',
  -- name = "indent-blankline",
  main = 'ibl', -- Required after v3.0.0
  enabled = true,
  lazy = true,
  event = { 'BufReadPost', 'BufNewFile' },
  opts = {
    indent = {
      char = '┊',
      smart_indent_cap = true,
      highlight = {
        'winter_blue',
      },
    },
    scope = {
      enabled = false,
    },
    viewport_buffer = {
      min = 100,
      max = 600,
    },
  },
  config = function(_, opts)
    local hooks = require 'ibl.hooks'

    hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
      vim.api.nvim_set_hl(0, 'winter_blue', { fg = '#252535' })
    end)

    local ibl_ok, ibl = pcall(require, 'ibl')

    if not ibl_ok then
      print "Error loading 'indent-blankline'."
      return
    end

    ibl.setup(opts)
  end,
}
```

### Expected behavior

No error, indent-newline setup completes successfully.

### Neovim version (nvim -v)

NVIM v0.11.0-dev

**Comment by lukas-reineke** [comment] 2024-11-12 10:36
Duplicate of https://github.com/lukas-reineke/indent-blankline.nvim/issues/936
Please make sure your Neovim version is up to date

**Closed by lukas-reineke** 2024-11-12 10:36 UTC
Labels: bug
