### ISSUE TITLE
breakindent (vim.opt.breakindent) breaks indent-blankline since `9433822`

### ISSUE THREAD

**Issue by GotaLoveFiraCode** [lukas-reineke/indent-blankline.nvim#816] opened 2024-01-01 16:41 UTC
### Problem

Errors at basically every event (`BufReadPost`, `CursorMoved`, etc.): `invalid key: virt_text_repeat_linebreak`.

### Steps to reproduce

`vim.opt.bri = true`. Then start doing stuff in files with indentation.

### Expected behavior

No errors. This can be fixed by using commits prior to `9433822`.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1750+ge5d7003b0 Build type: Release LuaJIT 2.1.1700008891 Run "nvim -V1 -v" for more info

**Comment by rudimusmaximus** [comment] 2024-01-01 19:18
Thanks for great plugin. Just a note, I had to go back a few as follows for workaround.
indent-blankline.nvim 1.46ms  start
        dir     /Users/rudimusmaximus/.local/share/nvim-config/lazy/indent-blankline.nvim
        url     https://github.com/lukas-reineke/indent-blankline.nvim
        version 3.4.1
        tag     v3.4.1
        branch  master
        commit  3084950
        readme  README.md
        help    |indent-blankline.txt|

**Comment by Danielkonge** [comment] 2024-01-01 21:06
I think the current code just checks if you are using neovim 0.9.x or 0.10 when checking if `virt_text_repeat_linebreak` is available, but `virt_text_repeat_linebreak` only got added to neovim 0.10 a bit more than a week ago, so you need a neovim version from within the last week (approximately) if you are on neovim 0.10. If you are using a 0.9.x there shouldn't be any problems. I think your current neovim 0.10 version is too old.

**Comment by lukas-reineke** [comment] 2024-01-02 00:10
Duplicate of #812

**Closed** 2024-01-02 00:10 UTC
Labels: bug
