### ISSUE TITLE
Doesn't work on previous versions of neovim 0.10.0

### ISSUE THREAD

**Issue by Stan-breaks** [lukas-reineke/indent-blankline.nvim#879] opened 2024-05-18 06:32 UTC
### Problem

This plugin breaks when using it neovim 0.9.4 because it uses iter ,a feature that was introduced in neovim 0.10.0. 
In this version of neovim iter is nil and the plugin is not functional.

### Steps to reproduce

install neovim through the apt package manager or look for the 0.9.4 version.
using lazy nvim configure indent-blankline at a plugin and everything else is default.

### Expected behavior

The plugin should function.

### Neovim version (nvim -v)

0.9.4

**Comment by mkalinski** [comment] 2024-05-18 07:20
"Duplicate of https://github.com/lukas-reineke/indent-blankline.nvim/issues/869"?

It feels like it would have been more rational to wait with update to 0.10.0 API for a week or so, so that 0.10.0 has time to trickle down to distro repos, where I would guess most people get their Neovim from.

Or make sure that IBL fails with a "Minimal supported Neovim version 0.10.0!" error, and not something that looks like a random bug.

Or at least pin issue #869.

Because these bug reports will keep getting opened.

**Comment by monoira** [comment] 2024-05-18 09:41
true.

whole LazyVim community is being annoyed because of this:

https://github.com/LazyVim/LazyVim/issues/3192

**Comment by lukas-reineke** [comment] 2024-05-18 14:24
Duplicate of #869 

Latest version should work with 0.9 again. But I make no guarantees, this plugin only officially supports the latest stable Neovim version.
If you do not want to update yet, please pin the version of this plugin.

**Closed by lukas-reineke** 2024-05-18 14:24 UTC
Labels: bug

**Comment by Stan-breaks** [comment] 2024-05-18 14:27
Thank you for your response and the help.
