### ISSUE TITLE
An error appears when opening a file

### ISSUE THREAD

**Issue by metal3d** [lukas-reineke/indent-blankline.nvim#872] opened 2024-05-17 08:56 UTC
### Problem

Since https://github.com/lukas-reineke/indent-blankline.nvim/commit/98f85638a669fd7f42f59a7283676391ab9b9ca3 there is an error opening files in NeoVim:

```
Failed to run `config` for indent-blankline.nvim

.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:428: attempt to call field 'iter' (a nil value)

# stacktrace:
  - /indent-blankline.nvim/lua/ibl/utils.lua:428 _in_ **tbl_join**
  - /indent-blankline.nvim/lua/ibl/config.lua:253 _in_ **merge_configs**
  - /indent-blankline.nvim/lua/ibl/config.lua:276 _in_ **set_config**
  - /indent-blankline.nvim/lua/ibl/init.lua:57 _in_ **setup**
  - vim/_editor.lua:0
  - /neo-tree.nvim/lua/neo-tree/utils/init.lua:732 _in_ **open_file**
  - /neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:729 _in_ **open**
  - /neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:751 _in_ **open_with_cmd**
  - /neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:760 _in_ **open**
  - /neo-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:184
```

### Steps to reproduce

I'm using LazyVim/starter, it installs indent-blankline. I then open a file with nvim

### Expected behavior

The error should disapear :)

### Neovim version (nvim -v)

0.9.4

**Comment by lukas-reineke** [comment] 2024-05-17 08:57
Duplicate of #869

**Closed by lukas-reineke** 2024-05-17 08:57 UTC
Labels: bug
