### ISSUE TITLE
Use of `vim.iter` breaks support for pre v0.10 nvim releases.

### ISSUE THREAD

**Issue by UtkarshVerma** [lukas-reineke/indent-blankline.nvim#878] opened 2024-05-18 01:06 UTC
### Problem

I updated this plugin today and noticed how it started crashing. A look at the logs revealed the following line to be the culprit.

https://github.com/lukas-reineke/indent-blankline.nvim/blob/master/lua/ibl/utils.lua#L428

### Steps to reproduce

nvim --clean -u min-init.lua :edit foo

### Expected behavior

Plugin runs without crashing.

### Neovim version (nvim -v)

0.9.5

**Comment by zgastley** [comment] 2024-05-18 01:42
+1 to this. Having same exact issue.

**Comment by JustSoursop** [comment] 2024-05-18 02:08
I also have same issue, 

```log

Failed to run `config` for indent-blankline.nvim

.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:428: attempt to call field 'iter' (a nil value)

# stacktrace:
  - /indent-blankline.nvim/lua/ibl/utils.lua:428 _in_ **tbl_join**
  - /indent-blankline.nvim/lua/ibl/config.lua:253 _in_ **merge_configs**
  - /indent-blankline.nvim/lua/ibl/config.lua:276 _in_ **set_config**
  - /indent-blankline.nvim/lua/ibl/init.lua:57 _in_ **setup**
  - vim/_editor.lua:0
  - /neo-tree.nvim/lua/neo-tree/utils/init.lua:732 _in_ **open_file**
  - /neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:729 _in_ **open**
  - /neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:751 _in_ **open_with_cmd**
  - /neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:760 _in_ **open**
  - /neo-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:184
```
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/137609917/a74e8707-0336-4700-b7da-aeee65091602)

**Comment by lukas-reineke** [comment] 2024-05-18 02:14
Duplicate of #869

**Closed by lukas-reineke** 2024-05-18 02:14 UTC
Labels: bug
