### ISSUE TITLE
[lua branch] Indent lines cover text when scrolling horizontally

### ISSUE THREAD

**Issue by RRethy** [lukas-reineke/indent-blankline.nvim#104] opened 2021-05-07 03:07 UTC
When using `zl` and `zh` to scroll horizontally the indents don't scroll.

Take the following text and add to the comment so that the text goes off screen, then use `zl` a few times to move the window right and parts of the text at the start will be covered by the indent lines.

```lua
if true then
    print("Hello, World!") -- a long line that goes out of screen
end
```

I'm not sure if there is a fix for this since it's virtual text behaviour, just thought i'd throw it out there.

Screenshots:

<img width="1392" alt="Screen Shot 2021-05-06 at 11 05 08 PM" src="https://user-images.githubusercontent.com/21000943/117392267-b7c41680-aebf-11eb-9b7d-95f81865d05a.png">
<img width="1392" alt="Screen Shot 2021-05-06 at 11 05 11 PM" src="https://user-images.githubusercontent.com/21000943/117392265-b692e980-aebf-11eb-8320-8892933e5215.png">

Highlight groups:

```
:hi IndentBlanklineChar                                                                                                                               
IndentBlanklineChar xxx guifg=#565c64                                                                                                                 
:hi IndentBlanklineContextChar                                                                                                                        
IndentBlanklineContextChar xxx cterm=nocombine gui=nocombine guifg=#c678dd                                                                            
:hi IndentBlanklineSpaceChar                                                                                                                          
IndentBlanklineSpaceChar xxx cterm=nocombine ctermfg=12 gui=nocombine guifg=#565c64                                                                   
:hi IndentBlanklineSpaceCharBlankline                                                                                                                 
IndentBlanklineSpaceCharBlankline xxx cterm=nocombine ctermfg=12 gui=nocombine guifg=#565c64  
```
I tried but failed to get transparency, not sure if i'm just missing something.

**Comment by lukas-reineke** [comment] 2021-05-07 04:12
duplicate of #51

**Closed by lukas-reineke** 2021-05-07 04:12 UTC
