### ISSUE TITLE
indentlines shown for excluded filestypes

### ISSUE THREAD

**Issue by WhyNotHugo** [lukas-reineke/indent-blankline.nvim#113] opened 2021-05-24 20:08 UTC
I'm seeing lines rendered filetypes that are excluded (particularly, `man`):

```
:let g:indent_blankline_filetype_exclude
g:indent_blankline_filetype_exclude ['man']
:set ft
filetype=man
```

![image](https://user-images.githubusercontent.com/730811/119402087-f3d2e600-bccb-11eb-89fe-3289e4e1dca8.png)

Any hints on whether I'm doing something wrong here?

**Comment by lukas-reineke** [comment] 2021-05-25 02:14
I can't reproduce.
Can you make a minimal `init.vim` (or `init.lua`) to reproduce the issue?

**Comment by WhyNotHugo** [comment] 2021-05-25 07:36
Honestly, I'm rather confused on how `neovim` and its plugin loading works.

I tried using `export MANPAGER="nvim -u /dev/null -c 'set ft=man' - "`, and then running `man man`, and neovim doesn't load my settings, but _does_ load installed plugins.

**Comment by lukas-reineke** [comment] 2021-05-25 08:13
If you don't want to load plugins, you should use `-u NONE`

**Comment by lukas-reineke** [comment] 2021-08-15 09:43
Closing this as there is no update

**Closed by lukas-reineke** 2021-08-15 09:43 UTC

**Comment by piotr-machura** [comment] 2021-08-20 23:58
Hey, I have encountered the same issue trying to use neovim as manpager. Here is a minimal init.vim:
```vim
call plug#begin(stdpath('data').'/vim-plug')
Plug 'lukas-reineke/indent-blankline.nvim'
let g:indent_blankline_buftype_exclude = ['nofile']
let g:indent_blankline_filetype_exclude = ['man']
call plug#end()
```
Write that to min.vim and do `MANPAGER="nvim -u min.vim -c 'set ft=man' -" man ls`.
The output is something like:
![screenshot_548973](https://user-images.githubusercontent.com/59394665/130303299-f851d131-ec63-41f0-a42d-c84ce246c83a.png)
and after doing `:IndentBlanklineDisable` the blue lines dissapear:
![screenshot_572301](https://user-images.githubusercontent.com/59394665/130303338-d14a1abc-5ec2-4604-8b54-879dc7193fcd.png)

Interestingly, the lines do not continue beyond the "original" buffer section:
![screenshot_594672](https://user-images.githubusercontent.com/59394665/130303412-237df1f1-0290-4b85-a51c-77c6df909a02.png)
and also doing `:IndentBlanklineToggle` actually enables them to continue:
![screenshot_140796](https://user-images.githubusercontent.com/59394665/130303598-e8c7f53a-b6c4-4cf3-b4af-d06427ea7fc2.png)

which makes me think the initial lines are just some visual artifact, but neither `:IndentBlanklineRefresh` or `:redraw!` makes them go away.
