### ISSUE TITLE
Selection misbehavior

### ISSUE THREAD

**Issue by oblitum** [lukas-reineke/indent-blankline.nvim#318] opened 2021-11-10 22:18 UTC
Hi, thanks for the project.

I'm hitting the following problem with the plugin:

`Correct behavior (plugin turned off):`
![correct](https://user-images.githubusercontent.com/1269815/141201952-12275e1c-56f1-4151-95a6-b1c3febba477.gif)

`Incorrect behavior (plugin turned on):`
![incorrect](https://user-images.githubusercontent.com/1269815/141201944-6166858f-1d99-46da-8acc-02a64e475e9f.gif)

Gif produced while over my [init.lua#L878](https://codeberg.org/oblitum/dotfiles/src/commit/daa705616a912a36ae96ce4d3d3863fb479c64d5/.config/nvim/init.lua#L878). I'm not sure exactly what kind of code being selected causes that, it generally involves braces, but it happens erratically.

**Comment by lukas-reineke** [comment] 2021-11-11 02:11
This is a duplicate of #59 
Take a look there for more information and a workaround.

**Closed by lukas-reineke** 2021-11-11 02:11 UTC

**Comment by oblitum** [comment] 2021-11-11 02:34
@lukas-reineke thx, indeed, https://github.com/lukas-reineke/indent-blankline.nvim/issues/59#issuecomment-806374954 fixes it.

**Comment by oblitum** [comment] 2021-11-11 18:49
@lukas-reineke I notice you changed the tittle on #59. To avoid confusion, the "misbehavior" I've referred to isn't just strict to not clearing up. You may notice there's also a weird/unwanted selection expansion.
