### ISSUE TITLE
[lazy.nvim]: Failed to run config for indent-blankline.nvim because field 'iter' is a nill value 

### ISSUE THREAD

**Issue by GopalVerma1303** [lukas-reineke/indent-blankline.nvim#873] opened 2024-05-17 09:07 UTC
### Problem

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/67120469/bdda1d38-42fb-43d1-9bb9-41f75f73476e)

### Steps to reproduce

1. `git clone https://github.com/GopalVerma1303/dotconfigs.git` in your root folder (~)
2. `mv ~/.config/nvim ~/.config/nvim.backup` backup for ur current nvim config
3. `mv ~/dotconfigs/nvim.windows ~/.config/nvim` move my nvim config (windows) to urs ~/.config
4. `nvim` for opening neovim with my config 
5. Open any file, u will see a notice window on the top right showing the error as shown in the above image.

### Expected behavior

1. Should not show this error.
2. Provide the features as expected.

### Neovim version (nvim -v)

v0.9.5

**Comment by lukas-reineke** [comment] 2024-05-17 09:11
duplicate of #869

**Closed by lukas-reineke** 2024-05-17 09:11 UTC
Labels: bug

**Comment by GopalVerma1303** [comment] 2024-05-17 09:31
Thanks guys!
