### ISSUE TITLE
Error When Opening Files in Nvim

### ISSUE THREAD

**Issue by Freaksed** [lukas-reineke/indent-blankline.nvim#949] opened 2024-11-18 21:44 UTC
### Problem

When I open my files in nvim I have started seeing this error
│ Failed to run config for indent-blankline.nvim                │
│                                                               │
│ .../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:2…│
│                                                               │
│ # stacktrace:                                                 │
│   - vim/shared.lua:0 in validate                              │
│   - /indent-blankline.nvim/lua/ibl/utils.lua:22 in validate   │
│   - /indent-blankline.nvim/lua/ibl/utils.lua:34 in validate_c…│
│   - /indent-blankline.nvim/lua/ibl/config.lua:131 in validate…│
│   - /indent-blankline.nvim/lua/ibl/config.lua:273 in set_conf…│
│   - /indent-blankline.nvim/lua/ibl/init.lua:57 in setup       │
│   - vim/_editor.lua:0 in cmd                                  │
│   - /persistence.nvim/lua/persistence/init.lua:88 in load     │
│   - lua:1                                                     │
│   - vim/_editor.lua:0 in cmd                                  │
│   - /dashboard-nvim/lua/dashboard/theme/doom.lua:24           │

### Steps to reproduce

update plugins, open a file

### Expected behavior

no error message

### Neovim version (nvim -v)

v0.11.0-dev-973+gb7e8966715

**Comment by lukas-reineke** [comment] 2024-11-18 23:54
Duplicate of https://github.com/lukas-reineke/indent-blankline.nvim/issues/936
Please make sure your Neovim version is up to date

**Closed by lukas-reineke** 2024-11-18 23:54 UTC
Labels: bug
