### ISSUE TITLE
[Lua branch] Indent guides covering text

### ISSUE THREAD

**Issue by NTBBloodbath** [lukas-reineke/indent-blankline.nvim#62] opened 2021-03-22 07:07 UTC
Hi, I'm having the same problem as issue #44, but I don't use Vim-Plug. Any ideas how to fix it?

There is some information if it is useful:
- Platform: Linux (Fedora 34)
- Neovim: `NVIM v0.5.0-dev+1165-ge5bef5974`

Thanks in advance :slightly_smiling_face:

**Comment by lukas-reineke** [comment] 2021-03-22 08:01
I need some more information.
Can you share the file where this is happening? And maybe a screenshot of what is happening

**Comment by ratheesh** [comment] 2021-03-22 13:24
@NTBBloodbath Can you check if this is related to issue #43 ?

**Comment by NTBBloodbath** [comment] 2021-03-22 20:24
> Can you share the file where this is happening? And maybe a screenshot of what is happening

That's happening in all my files, but I mainly work with Vimscript, Lua, Python and JavaScript.

![What is happening with my code](https://i.postimg.cc/mZ5hJQrt/Screenshot-20210322-162204.png)

**Comment by NTBBloodbath** [comment] 2021-03-22 20:26
> Can you check if this is related to issue #43 ?

No, it is not related to that issue but yes with the issue #44 :slightly_smiling_face:

**Comment by lukas-reineke** [comment] 2021-03-23 01:39
Can you paste the code of a file where this is happening here? Doesn't have to be everything, just make a small file to reproduce this.

Also make sure the plugin is up to date. The bug in #44 is fixed, either your plugin is not updated, or this is unrelated.

**Comment by NTBBloodbath** [comment] 2021-03-23 01:53
Here for example, if we go to the end of line 6 as it is the longest, the buffer will roll to the right (as it would normally happen when seeing a very long line) and the text of the other lines, including that one, is covered by the space and indentation characters. 

```lua
1 | buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
2 | buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
3 | buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
4 | buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
5 | buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
6 | buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
7 | buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
```

The plugin is up to date, I installed it yesterday and updated it very recently. The way this is related to issue #44 is what happens (that the text is covered when going to the end of long lines), since I do not use Vim-Plug so the case would not be entirely the same

**Comment by lukas-reineke** [comment] 2021-03-23 02:10
Oh I see, it is because you are scrolling horizontally.
This is a duplicate of #51

Sorry there is no fix for this yet, this needs to be implemented on the neovim side. Here is the ticket https://github.com/neovim/neovim/issues/14050

I'll close this ticket. If there is anything else you want to add, comment in #51

**Closed by lukas-reineke** 2021-03-23 02:10 UTC
