### ISSUE TITLE
`cursorline` highlight is not cleared after the cursor is moved

### ISSUE THREAD

**Issue by ChristianChiarulli** [lukas-reineke/indent-blankline.nvim#59] opened 2021-03-18 18:28 UTC
I'm not really sure how to explain this but for some black spaces some of the highlight gets left behind

![image](https://user-images.githubusercontent.com/29136904/111677928-1b9e5d00-87f6-11eb-8110-fe5d83fc7aa2.png)

**Comment by ChristianChiarulli** [comment] 2021-03-18 18:29
And if I mouse click in the buffer it disappears.

**Comment by lukas-reineke** [comment] 2021-03-19 01:10
Is that cursorline highlight?
I can't reproduce this.

Rendering bugs are very probably bugs in Neovim. Can you try to reproduce this in a clean environment?

`nvim -u NORC`

and then run this, it should write `hello world` as virtual text in the first line.
```
:lua ns_id = vim.api.nvim_create_namespace("foo")
:lua vim.api.nvim_buf_set_extmark(0, ns_id, 0, 0, { virt_text={{'hello world', 'String'}}, virt_text_pos='overlay'})
```

Does it happen for that as well?

**Comment by kristijanhusak** [comment] 2021-03-21 12:31
I can confirm this happens to me also, randomly. Once I move around it clears itself. Maybe some redrawing is needed, not sure.

**Comment by ChristianChiarulli** [comment] 2021-03-21 18:13
Yea I’ll have to test without some plugins. I haven’t tried barebones yet. I’m glad someone else can confirm the issue.

**Comment by timbedard** [comment] 2021-03-21 18:16
Same issue.

@lukas-reineke I tried your virtual text experiment. It doesn't retain the highlight the same way that the blank lines do when using indent-blankline either with an empty config or with indent-blankline, whether the virtual text line has text or is blank.

**Comment by lukas-reineke** [comment] 2021-03-22 01:52
I'm still not sure what highlight we are talking about. Is it cursorline or visual selection?
Can you also share what terminal emulator / neovim version / OS / tmux etc you are using?

**Comment by ChristianChiarulli** [comment] 2021-03-22 02:57
It’s the cursorline highlight. No tmux, alacritty, arch Linux.

**Comment by ahmedkhalf** [comment] 2021-03-22 05:52
I am also having a similar issue when scrolling down (go file w/tabs).

![image](https://user-images.githubusercontent.com/36672196/111946107-4b01e200-8af4-11eb-8eb7-b89ed3d9a03d.png)

**Comment by lukas-reineke** [comment] 2021-03-22 08:13
:thinking: 
I still can't reproduce it at all. I tried with alacritty and kitty on arch. Different filetypes. Tabs and spaces. Different nvim versions.

Again, as this looks like a rendering issue, I am 99% sure that this is an issue with Neovim directly, not with this plugin.
But without being able to reproduce, I don't really know where to start looking.

@bfredl do you have any idea what could cause this?

**Comment by ChristianChiarulli** [comment] 2021-03-23 15:48
Clarification: it only happens when there is no white space on the line. If I add some white space the left over block doesn't show up.

**Comment by ChristianChiarulli** [comment] 2021-03-23 15:58
![image](https://user-images.githubusercontent.com/29136904/112177012-f97a5580-8bce-11eb-8105-d3865ff53d70.png)

definitely cursorline background highlight, disappears on redraw.

**Comment by lukas-reineke** [comment] 2021-03-25 03:12
I investigated a bit more. The key point here is the `hl_mode = "combine"`
I can reproduce it now with a clean `init.vim`

I opened a bug in nvim: https://github.com/neovim/neovim/issues/14209

Thanks for all the information

**Comment by ChristianChiarulli** [comment] 2021-03-25 04:32
Awesome, thanks for taking the time to look into this.

**Comment by lukas-reineke** [comment] 2021-03-25 05:28
I was wondering why it is not happening for me, so looked a bit more.

Setting `colorcolumn` fixes it!

So as a workaround for now just set `colorcoumn`. You can set it to a very large number so you don't actually see it if you don't want to.
`set colorcolumn=99999`

**Comment by timbedard** [comment] 2021-03-25 06:27
For anyone else finding this in the interim that happens to be setting it from lua, remember that colorcolumn is a comma-separated list in viml, so you have to set it as a string in lua (and remember that it's a window option).
```lua
vim.wo.colorcolumn = "99999"
```

**Comment by Joarell** [comment] 2021-11-23 22:01
![image](https://user-images.githubusercontent.com/42722369/143135708-40a4fa1e-6e74-4637-8a9b-6d25adf91aec.png)
Hi there!
First of all, congrats man!
You are awesome!

So, how can hidden those blank parts from the code body?
I've tried to use the highlights in indentation, however those blank parts are always rising up on the among the code.
Thank you for the plugin, man!
Be fine!

**Comment by lukas-reineke** [comment] 2022-01-17 05:04
Fixed in Neovim :rocket:

**Closed by lukas-reineke** 2022-01-17 05:04 UTC
