### ISSUE TITLE
[Bug] indent-blankline does not show indentline after moving the view to the right and moving back

### ISSUE THREAD

**Issue by Bekaboo** [lukas-reineke/indent-blankline.nvim#537] opened 2023-02-05 19:00 UTC
If the cursor is on a long line and I use `zL` to move the view to the right, the guidelines drawn by indent-blankline disappears after I move back.

Here is my config for indent-blankline:

```lua
require('indent_blankline').setup({
  show_current_context = false,
  show_trailing_blankline_indent = false,
  indent_blankline_use_treesitter = false,
})
```

and here is a short video that demonstrate the bug:

https://user-images.githubusercontent.com/76579810/216839248-2c0ed6d4-ba8e-4f0d-8a5d-e511c5675573.mp4

**Comment by lukas-reineke** [comment] 2023-02-06 01:18
duplicate of https://github.com/lukas-reineke/indent-blankline.nvim/issues/489

**Closed by lukas-reineke** 2023-02-06 01:18 UTC
