### ISSUE TITLE
Ghost highlighting when using cursorline

### ISSUE THREAD

**Issue by imsofi** [lukas-reineke/indent-blankline.nvim#101] opened 2021-05-01 23:03 UTC
Using the latest indent-blankline from the lua branch together with [folke/tokyonight.nvim](https://github.com/folke/tokyonight.nvim) as the theme.

When `vim.wo.cursorline = true` and `vim.cmd 'colorscheme = toykonight'` is set it will cause blank indentlines to keep the background highlighting from cursorline when scrolled past.

Example:
![Before scrolling](https://user-images.githubusercontent.com/20756843/116796747-4c550000-aadf-11eb-8e83-0b517c8a05b9.png)
![After scrolling](https://user-images.githubusercontent.com/20756843/116796746-4bbc6980-aadf-11eb-901b-05eeb15938f2.png)

Theres also an issue open on [folke/tokyonight.nvim #29](https://github.com/folke/tokyonight.nvim/issues/29)

**Comment by lukas-reineke** [comment] 2021-05-02 03:49
This is a duplicate of #59

look there for updates and a workaround

**Closed by lukas-reineke** 2021-05-02 03:49 UTC
