### ISSUE TITLE
v3: horizontal scroll defects

### ISSUE THREAD

**Issue by davidosomething** [lukas-reineke/indent-blankline.nvim#622] opened 2023-09-05 15:42 UTC
![Screenshot_20230905_113953](https://github.com/lukas-reineke/indent-blankline.nvim/assets/609213/5c7cba3b-f0b9-4fd2-97bb-a9bfee3a7744)
![Screenshot_20230905_114028](https://github.com/lukas-reineke/indent-blankline.nvim/assets/609213/eb90a275-7b01-4d90-b21c-b436241974f9)

on a thin window, do some horizontal scrolling and the first char of some lines gets replaced by indent guide

and do some jumping back to first char with `0` and the guides get wrecked

this issue actually exists in other plugins too, like hlchunk

**Comment by lukas-reineke** [comment] 2023-09-06 00:16
I can't reproduce this, there is logic to handle horizontal scrolling.

How do you scroll, with the mouse?
Is the buffer active when you scroll?
Do you have the same buffer open in more than one window?

**Comment by davidosomething** [comment] 2023-09-06 00:22
strange i cannot reproduce the first issue now

but the second issue is reproducable with the same buffer open in two thin windows
scroll the right buffer and the indent guides change for both windows

**Comment by lukas-reineke** [comment] 2023-09-06 00:47
> but the second issue is reproducable with the same buffer open in two thin windows

Yes, this is a limitation of what is currently possible in Neovim.
Virtual text does not scroll like normal text.
I need to calculate the horizontal scroll position and generate the virtual text with it.
But this means it is ever only going to look correct in one window. If you have the same buffer open in 2 windows with different scroll position, one of them will be wrong.

There is an issue for this here
https://github.com/neovim/neovim/issues/14050

**Comment by meator** [comment] 2023-09-17 06:05
I am encountering the same problem. I don't have the same buffer in two windows. Is there a way to manually reset indent-blankline?

**Comment by lukas-reineke** [comment] 2023-09-18 03:50
Please provide steps to reproduce the issue with a single buffer

**Comment by lukas-reineke** [comment] 2023-10-04 04:42
closing this
with 2 buffers, this is expected
with 1 buffer, I can't reproduce it

**Closed by lukas-reineke** 2023-10-04 04:42 UTC
