### ISSUE TITLE
Indent lines not showing since the last update

### ISSUE THREAD

**Issue by Gael101** [lukas-reineke/indent-blankline.nvim#160] opened 2021-08-03 14:44 UTC
I just ran packer update and I dont have any indent lines anymore , here's my config (i'm using LunarVim & Packer )
```lua
    "lukas-reineke/indent-blankline.nvim",
    event = "BufRead",
    setup = function()
      vim.g.indent_blankline_filetype_exclude = {"help", "terminal", "dashboard"}
      vim.g.indent_blankline_buftype_exclude = {"terminal"}
      vim.g.indent_blankline_show_trailing_blankline_indent = false
      vim.cmd [[highlight IndentOne guifg=#BF616A guibg=NONE gui=nocombine]]
      vim.cmd [[highlight IndentTwo guifg=#D08770 guibg=NONE gui=nocombine]]
      vim.cmd [[highlight IndentThree guifg=#EBCB8B guibg=NONE gui=nocombine]]
      vim.cmd [[highlight IndentFour guifg=#A3BE8C guibg=NONE gui=nocombine]]
      vim.cmd [[highlight IndentFive guifg=#5E81AC guibg=NONE gui=nocombine]]
      vim.cmd [[highlight IndentSix guifg=#88C0D0 guibg=NONE gui=nocombine]]
      vim.cmd [[highlight IndentSeven guifg=#B48EAD guibg=NONE gui=nocombine]]
      vim.g.indent_blankline_char = "│"
      vim.g.indent_blankline_char_highlight_list = {
        "IndentOne", "IndentTwo", "IndentThree", "IndentFour", "IndentFive",
        "IndentSix", "IndentSeven"
      }
      vim.g.indent_blankline_show_first_indent_level = true
      vim.g.indent_blankline_filetype_exclude = {
        "startify", "dashboard", "dotooagenda", "log", "fugitive", "gitcommit",
        "packer", "vimwiki", "markdown", "json", "txt", "vista", "help",
        "todoist", "NvimTree", "peekaboo", "git", "TelescopePrompt", "undotree",
        "flutterToolsOutline", "" -- for all buffers without a file type
      }
      vim.g.indent_blankline_show_trailing_blankline_indent = false
      vim.g.indent_blankline_show_current_context = true
      vim.g.indent_blankline_context_patterns = {
        "class", "function", "method", "block", "list_literal", "selector",
        "^if", "^table", "if_statement", "while", "for"
      }
    end
```
Here's the message I get if I activate debug mode :
```bash 
.../opt/indent-blankline.nvim/lua/indent_blankline/init.lua:112: attempt to perform arithmetic on a nil value
```

**Comment by lukas-reineke** [comment] 2021-08-03 15:28
hmm I can't reproduce this.
But this would happen when the setup function doesn't get run correctly. I fixed an issue with this ~1 hour ago, can you make sure you are on the latest version?

It might also be related to the lazy loading, but I tried it in my setup, and it works fine, so not sure.


You can call the setup function directly, and it should fix the issue. This is the recommended way to configure the plugin now anyway.

```lua
require("indent_blankline").setup {
  filetype_exclude = {"help", "terminal", "dashboard"},
  ...
}
```

**Comment by ayamir** [comment] 2021-08-03 16:11
> I just ran packer update and I dont have any indent lines anymore , here's my config (i'm using LunarVim & Packer )
> 
> ```lua
>     "lukas-reineke/indent-blankline.nvim",
>     event = "BufRead",
>     setup = function()
>       vim.g.indent_blankline_filetype_exclude = {"help", "terminal", "dashboard"}
>       vim.g.indent_blankline_buftype_exclude = {"terminal"}
>       vim.g.indent_blankline_show_trailing_blankline_indent = false
>       vim.cmd [[highlight IndentOne guifg=#BF616A guibg=NONE gui=nocombine]]
>       vim.cmd [[highlight IndentTwo guifg=#D08770 guibg=NONE gui=nocombine]]
>       vim.cmd [[highlight IndentThree guifg=#EBCB8B guibg=NONE gui=nocombine]]
>       vim.cmd [[highlight IndentFour guifg=#A3BE8C guibg=NONE gui=nocombine]]
>       vim.cmd [[highlight IndentFive guifg=#5E81AC guibg=NONE gui=nocombine]]
>       vim.cmd [[highlight IndentSix guifg=#88C0D0 guibg=NONE gui=nocombine]]
>       vim.cmd [[highlight IndentSeven guifg=#B48EAD guibg=NONE gui=nocombine]]
>       vim.g.indent_blankline_char = "│"
>       vim.g.indent_blankline_char_highlight_list = {
>         "IndentOne", "IndentTwo", "IndentThree", "IndentFour", "IndentFive",
>         "IndentSix", "IndentSeven"
>       }
>       vim.g.indent_blankline_show_first_indent_level = true
>       vim.g.indent_blankline_filetype_exclude = {
>         "startify", "dashboard", "dotooagenda", "log", "fugitive", "gitcommit",
>         "packer", "vimwiki", "markdown", "json", "txt", "vista", "help",
>         "todoist", "NvimTree", "peekaboo", "git", "TelescopePrompt", "undotree",
>         "flutterToolsOutline", "" -- for all buffers without a file type
>       }
>       vim.g.indent_blankline_show_trailing_blankline_indent = false
>       vim.g.indent_blankline_show_current_context = true
>       vim.g.indent_blankline_context_patterns = {
>         "class", "function", "method", "block", "list_literal", "selector",
>         "^if", "^table", "if_statement", "while", "for"
>       }
>     end
> ```
> 
> Here's the message I get if I activate debug mode :
> 
> ```shell
> .../opt/indent-blankline.nvim/lua/indent_blankline/init.lua:112: attempt to perform arithmetic on a nil value
> ```

remove `event = "BufRead"`, add `opt = true`.

**Comment by cryptomilk** [comment] 2021-08-03 17:37
I have the same issue.

packer.nvim (with lazy loading):
```lua
    use {
        'lukas-reineke/indent-blankline.nvim',
        config = 'require("plugins.indent-blankline")',
        cmd = { 'IndentBlanklineToggle', 'IndentBlanklineRefresh' }
    }
```

plugins/indent-blanline.lua:
```lua
if not pcall(require, 'indent_blankline') then
  return
end

require('indent_blankline').setup {
    enabled = false,
    char = '┊',
    char_highlight_list = {'Keyword', 'Identifier', 'Type', 'diffAdded'},
    space_char = ' ',
    show_first_indent_level = false,
    show_current_context = true,
}
```

Calling IndentBlanklineToggle loads the plugin but it doesn't show the indent guidelines. Toggling it again to disable it gives the following error:

```
Error executing lua indent-blankline.nvim/lua/indent_blankline/commands.lua:35: Expected lua number
```

**Comment by ram02z** [comment] 2021-08-03 18:04
Adding `require("indent_blankline").init()` to the top of my config function in Packer fixes the issue.

**Comment by lukas-reineke** [comment] 2021-08-04 01:50
> Adding require("indent_blankline").init() to the top of my config function in Packer fixes the issue.

Then it is related to the lazy loading.
The plugin normally runs init on `VimEnter`, but I guess because you lazy load, this never happens.
Still weird that I can't reproduce it myself..

I will add this to the readme.

**Comment by lukas-reineke** [comment] 2021-08-04 03:48
I made a PR #161 to hopefully fix this without the need to add `require("indent_blankline").init()`

Can someone try that branch and see if it works?

It should now work with
1. normal sync loading, same as before
2. lazy loading with variables
3. lazy loading with setup function
4. lazy loading with no config at all

**Comment by ayamir** [comment] 2021-08-04 04:46
> * lazy loading with variables
> * lazy loading with setup function

I tested `bug/lazy-loading` branch successfully.

**Comment by lukas-reineke** [comment] 2021-08-04 13:48
Merged the fix into master now

Thanks for checking that it worked

**Closed** 2021-08-04 13:47 UTC

**Comment by dmitmel** [comment] 2021-08-07 11:22
Hi, is it intentional that `:IndentBlanklineRefresh!' is not ran on `VimEnter` now? This results in a bug when you load a session, for example, and the session has splits, the indentation guides are rendered only in the current window.

**Comment by lukas-reineke** [comment] 2021-08-07 12:39
I removed `VimEnter` because it caused issues with lazy loading, and I thought `BufWinEnter` would cover all the cases.
I think I could add it back now though :thinking:
