### ISSUE TITLE
Error after updating using Lazy

### ISSUE THREAD

**Issue by gfvioli** [lukas-reineke/indent-blankline.nvim#870] opened 2024-05-17 06:53 UTC
### Problem

The plugin was working flawlessly until I updated all packages using Lazy today. My config hasn't changed but now I get this error: 
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/96206151/4ec33731-c24d-409e-a8cb-e19a0e8e5218)

For reference, this is my config 
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/96206151/b834ce33-d3c6-4318-af4d-5875d81c9bc1)

I tried changing the lazy-lock.json commit reference to the one suggested on this [post](https://github.com/lukas-reineke/indent-blankline.nvim/discussions/692). That didn't work.

### Steps to reproduce

Error happens immediately after I open nvim

### Expected behavior

No error

### Neovim version (nvim -v)

v0.9.5

**Comment by perogycook** [comment] 2024-05-17 06:58
Getting same error here.  Neovim 0.9.5, completely stock LazyVim setup.

**Comment by lukas-reineke** [comment] 2024-05-17 07:00
duplicate of #869

**Closed by lukas-reineke** 2024-05-17 07:00 UTC
Labels: bug
