### ISSUE TITLE
Arabic text is concealed when indented

### ISSUE THREAD

**Issue by avidseeker** [lukas-reineke/indent-blankline.nvim#827] opened 2024-01-13 14:53 UTC
### Problem

Arabic text in Latex buffer not showing when indented and while in Arabic mode (`:set arabic`).

### Steps to reproduce

init.vim:
```vim
call plug#begin('~/.local/share/nvim/plugged')
	Plug 'lukas-reineke/indent-blankline.nvim'
call plug#end()

lua << END
require("ibl").setup { scope = { highlight = highlight } }
END
```

buff.tex:
```latex
\documentclass{article}

\begin{document}
	تجربة كتابة عربية
\end{document}
```

nvim -u init.vim -c ':set arabic' buff.tex

### Expected behavior

Indented sentence not showing up.

### Neovim version (nvim -v)

NVIM v0.9.5

**Comment by lukas-reineke** [comment] 2024-01-15 01:54
Can you describe what the problem is? I can't read arabic, but this looks correct to me

![2024-01-15_10-51](https://github.com/lukas-reineke/indent-blankline.nvim/assets/12900252/5144ea52-483b-425f-a2ed-75d0674dd7ea)

**Comment by avidseeker** [comment] 2024-01-15 22:46
The problem is that all indented Arabic characters are invisible (See attached screenshot). Tested this on Kitty, and st. Are you sure you ran `nvim -u init.vim -c ':set arabic' buff.tex` with the `init.vim`? And what terminal emulator did you use? 

Before `:set arabic`:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/67508272/2c91c7b1-052a-4b1c-871a-5d3637c18cd2)


After `:set arabic`:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/67508272/7247cd05-e044-4d99-b646-3c70faada7dc)

**Comment by lukas-reineke** [comment] 2024-01-16 01:20
Sorry, I can't reproduce the issue. I am using Kitty as well. I don't think this is an issue with indent-blankline.

When testing, make sure you also use `--clean`, to skip all other plugins.

**Comment by lukas-reineke** [comment] 2024-01-16 14:02
You need to explicitly include your plugin manager as well.

You can use this [minimal reproduction template](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template#minimal-config)

**Comment by avidseeker** [comment] 2024-01-16 15:48
Using `nvim --clean -u min-init.lua -c ':set arabic' buff.tex` on Kitty v0.31.0 and NVIM v0.9.5:

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/67508272/3db0277c-eb68-4851-a12d-e09587f6dece)

**Comment by lukas-reineke** [comment] 2024-01-17 00:58
I can reproduce it now :+1:
This is an issue with specifically Neovim 0.9.5, other versions work, that's why I couldn't reproduce it at first.
It is fixed in the nightly version, so you'll have to use that for now, or wait until the next release.

There is nothing I can do here, so I'll close the issue.

**Closed by lukas-reineke** 2024-01-17 00:58 UTC
Labels: bug
