### ISSUE TITLE
indent-blankline "failed to run config" after update lazyvim

### ISSUE THREAD

**Issue by davidgao7** [lukas-reineke/indent-blankline.nvim#875] opened 2024-05-17 15:10 UTC
### Problem

Hello everyone, thanks for making this awesome plugin! I updated lazyvim this morning and got indent-blankline `failed to run config`
I also asked in the lazyvim community and kind of found the answer. 

*here are some stack trace from indent-blankline.nvim if it could help debug* :)
[discussion in lazy community](https://github.com/LazyVim/LazyVim/discussions/3200)

Good luck on fixing bug!

### Steps to reproduce

run sync in lazyvim and then open a file in any language

### Expected behavior

see the invisibles,indent, a line surrounding functions, etc

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1703358377

**Comment by lukas-reineke** [comment] 2024-05-17 15:17
Duplicate of #869

**Comment by sfrique** [comment] 2024-05-17 15:17
duplicate of  #869

**Comment by z0tedd** [comment] 2024-05-17 15:17
You can use previous version of plugin. Create indent-blankline.lua file in your config and write the following text:
return {
  "lukas-reineke/indent-blankline.nvim",
  main = "ibl",
  commit = "29be0919b91fb59eca9e90690d76014233392bef",
}

**Closed as completed** 2024-05-17 15:17 UTC
Labels: bug
