### ISSUE TITLE
Indentation line aren't there when I first open a fold

### ISSUE THREAD

**Issue by FerasMaali** [lukas-reineke/indent-blankline.nvim#449] opened 2022-06-23 20:36 UTC
When opening a closed fold, the indentation lines aren't there for the area that was in the fold. Example:

Before opening the fold:
![image](https://user-images.githubusercontent.com/90563363/175394758-dc408ed5-89a9-43d6-92bd-752212501c3b.png)

After opening the fold:
![image](https://user-images.githubusercontent.com/90563363/175394811-68efd557-02fd-415b-b21d-cfc36f775def.png)

**Comment by lukas-reineke** [comment] 2022-06-24 02:54
Opening and closing folds has no autocmd. There is no way for indent blankline to know a fold as opened.
You can remap your mappings to open folds to also call `:IndentBlanklineRefresh`.

**Closed by lukas-reineke** 2022-06-24 02:54 UTC

**Comment by FerasMaali** [comment] 2022-06-24 09:47
Thanks @lukas-reineke 
I used this in case someone faces this issue again in the future:

```lua
for _, keymap in pairs({
    'zo',
    'zO',
    'zc',
    'zC',
    'za',
    'zA',
    'zv',
    'zx',
    'zX',
    'zm',
    'zM',
    'zr',
    'zR',
}) do
    vim.api.nvim_set_keymap('n', keymap,  keymap .. '<CMD>IndentBlanklineRefresh<CR>', { noremap=true, silent=true })
end
```

**Comment by maciejzj** [comment] 2023-03-25 09:23
Thanks, sorry to be yet another person who creates a duplicate of this
