### ISSUE TITLE
Error when running config for indent-blankline.nvim: type: expected function, got string (HIGHLIGHT_SETUP)

### ISSUE THREAD

**Issue by marvinbelfort** [lukas-reineke/indent-blankline.nvim#952] opened 2024-11-22 17:02 UTC
### Problem

I'm encountering an issue after updating all plugins using Lazy in Neovim. The error occurs specifically with indent-blankline.nvim. Below are the details:

```code
Failed to run `config` for indent-blankline.nvim

.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:22: type: expected function: 0x72d7b997e8b0, got string (H
IGHLIGHT_SETUP)

# stacktrace:
  - vim/shared.lua:0 _in_ **validate**
  - /indent-blankline.nvim/lua/ibl/utils.lua:22 _in_ **validate**
  - /indent-blankline.nvim/lua/ibl/hooks.lua:61 _in_ **register**
  - .config/nvim/lua/config/plugins/indent-blankline.lua:19 _in_ **config**
  - .config/nvim/lua/config/lazy.lua:16
  - .config/nvim/lua/config/init.lua:2
  - .dotfiles/nvim/init.lua:3
```

Config File:

```lua
return {
    "lukas-reineke/indent-blankline.nvim",
    main = "ibl",
    opts = {},
    config = function()
        local highlight = {
            "RainbowRed",
            "RainbowYellow",
            "RainbowBlue",
            "RainbowOrange",
            "RainbowGreen",
            "RainbowViolet",
            "RainbowCyan",
        }

        local hooks = require "ibl.hooks"
        -- create the highlight groups in the highlight setup hook, so they are reset
        -- every time the colorscheme changes
        hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
            vim.api.nvim_set_hl(0, "RainbowRed", { fg = "#E06C75" })
            vim.api.nvim_set_hl(0, "RainbowYellow", { fg = "#E5C07B" })
            vim.api.nvim_set_hl(0, "RainbowBlue", { fg = "#61AFEF" })
            vim.api.nvim_set_hl(0, "RainbowOrange", { fg = "#D19A66" })
            vim.api.nvim_set_hl(0, "RainbowGreen", { fg = "#98C379" })
            vim.api.nvim_set_hl(0, "RainbowViolet", { fg = "#C678DD" })
            vim.api.nvim_set_hl(0, "RainbowCyan", { fg = "#56B6C2" })
        end)

        vim.g.rainbow_delimiters = { highlight = highlight }
        require("ibl").setup { indent = { highlight = highlight, char = "▏" } } --⎪⎥⎢⎟⎜⏐⎜⎢⎥⎪⎮⎸⎹⏐-▕ │┃ 
        hooks.register(hooks.type.SCOPE_HIGHLIGHT, hooks.builtin.scope_highlight_from_extmark)
    end
}

```

### Steps to reproduce

Update plugins using Lazy with Neovim 0.11.0-dev.

### Expected behavior

The plugin loads without issues.

### Neovim version (nvim -v)

v0.11.0-dev-848+g09d76afe84

**Comment by avegancafe** [comment] 2024-11-22 18:55
Also same, trying to track down where in the code this change happened

**Comment by avegancafe** [comment] 2024-11-22 19:07
I think it has to do with this change: https://github.com/lukas-reineke/indent-blankline.nvim/commit/04e44b09ee3ff189c69ab082edac1ef7ae2e256c

Replacing [this block of code](https://github.com/lukas-reineke/indent-blankline.nvim/blob/master/lua/ibl/utils.lua#L18-L23) with just `vim.validate(spec)` fixes the issue @marvinbelfort . I'll open a PR to revert this, maybe it'll get accepted

**Comment by marvinbelfort** [comment] 2024-11-22 19:15
Thanks @avegancafe! It worked!

**Comment by lukas-reineke** [comment] 2024-11-23 00:59
Duplicate of #936
Please make sure your Neovim version is up to date

**Closed by lukas-reineke** 2024-11-23 00:59 UTC
Labels: bug
