### ISSUE TITLE
Errors opening .c & .cpp Files

### ISSUE THREAD

**Issue by SirGamsay** [lukas-reineke/indent-blankline.nvim#955] opened 2024-11-27 16:36 UTC
### Problem

Hello, suddenly today this Plugins seems to not work with `.c` and `.cpp` Files for me anymore. 

So just a `.lua` file with `require("ibl").setup()` changes nothing. It seems to be an actual Problem in `/home/meiko/.local/share/nvim/plugged/indent-blankline.nvim/after/ftplugin/c.lua`.

Is this reproducable for other People?
 

### Steps to reproduce

When opening those Files I just get

```
Error when executing "BufReadPost Autokommandos für "*"":
Error executing lua callback: /usr/local/share/nvim/runtime/filetype.lua:35: Error executing lua: /usr/local/share/nvim/runtime/filetype.lua:36: BufReadPost Autokommandos für
 "*"..FileType Autokommandos für "*"..function <SNR>1_LoadFTPlugin[20]..script /home/meiko/.local/share/nvim/plugged/indent-blankline.nvim/after/ftplugin/c.lua: Vim(runtime):
E5113: Error while calling lua chunk: ...are/nvim/plugged/indent-blankline.nvim/lua/ibl/utils.lua:22: type: expected function: 0x7c8e54a1b480, got string (SKIP_LINE)
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        ...are/nvim/plugged/indent-blankline.nvim/lua/ibl/utils.lua:22: in function 'validate'
        ...are/nvim/plugged/indent-blankline.nvim/lua/ibl/hooks.lua:61: in function 'register'
        .../nvim/plugged/indent-blankline.nvim/after/ftplugin/c.lua:3: in main chunk
        [C]: in function 'nvim_cmd'
        /usr/local/share/nvim/runtime/filetype.lua:36: in function </usr/local/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:35: in function </usr/local/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/local/share/nvim/runtime/filetype.lua:36: in function </usr/local/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:35: in function </usr/local/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:35: in function </usr/local/share/nvim/runtime/filetype.lua:10>
```

This does not happen, when I remove the indent-blankline Plugin with (in my Case) `:PlugClean`. However, it does not matter if I have the actual setup or not.

### Expected behavior

I would expect to be able to open my `.c` & `.cpp` Files.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-199+g488121109

**Comment by lukas-reineke** [comment] 2024-11-28 02:29
Duplicate of #936
Please make sure your Neovim version is up to date

**Closed by lukas-reineke** 2024-11-28 02:29 UTC
Labels: bug
