### ISSUE TITLE
Cursorline leaves artifacts on empty indent lines

### ISSUE THREAD

**Issue by sunjon** [lukas-reineke/indent-blankline.nvim#93] opened 2021-04-17 11:05 UTC
![](https://raw.githubusercontent.com/sunjon/images/master/indent_lines_artifacts.gif)
 With cursorline enabled, artifacts are momentarily left on indented lines without the guides.

My configuration is as follows:

```
vim.g.indent_blankline_use_treesitter = true
vim.g.indent_blankline_show_current_context  = false
vim.g.indent_blankline_char = "│"
vim.g.indent_blankline_filetype = {'json','lua', 'terraform'}
vim.g.indent_blankline_indent_level = 3
vim.g.indent_blankline_show_trailing_blankline_indent = false
vim.g.indent_blankline_show_first_indent_level = false
vim.cmd[[ hi IndentBlankLineChar guifg=#665c54 gui=nocombine ]]
vim.cmd[[ hi IndentBlankLineSpaceChar guifg=#00ff00 gui=nocombine ]]
vim.cmd[[ hi IndentBlankLineSpaceCharBlankLine guifg=#00ffff gui=nocombine ]]
vim.cmd[[ hi IndentBlankLineContextHighlight guifg=#e98d26 gui=nocombine ]]
```

**Comment by lukas-reineke** [comment] 2021-04-17 12:19
This is a duplicate of #59 take a look there

I'm closing this issue

**Closed by lukas-reineke** 2021-04-17 12:19 UTC
