### ISSUE TITLE
> in some files instead of |

### ISSUE THREAD

**Issue by FormalSnake** [lukas-reineke/indent-blankline.nvim#712] opened 2023-10-06 09:51 UTC
### Problem

<img width="1760" alt="Screenshot 2023-10-06 at 10 48 57" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/90651091/56317a25-9729-48ff-94ba-8695a5c73ceb">
And this is my config
```
local highlight = {
	"RainbowRed",
	"RainbowYellow",
	"RainbowBlue",
	"RainbowOrange",
	"RainbowGreen",
	"RainbowViolet",
	"RainbowCyan",
}
local hooks = require "ibl.hooks"
-- create the highlight groups in the highlight setup hook, so they are reset
-- every time the colorscheme changes
hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
	vim.api.nvim_set_hl(0, "RainbowRed", { fg = "#E06C75" })
	vim.api.nvim_set_hl(0, "RainbowYellow", { fg = "#E5C07B" })
	vim.api.nvim_set_hl(0, "RainbowBlue", { fg = "#61AFEF" })
	vim.api.nvim_set_hl(0, "RainbowOrange", { fg = "#D19A66" })
	vim.api.nvim_set_hl(0, "RainbowGreen", { fg = "#98C379" })
	vim.api.nvim_set_hl(0, "RainbowViolet", { fg = "#C678DD" })
	vim.api.nvim_set_hl(0, "RainbowCyan", { fg = "#56B6C2" })
end)

vim.g.rainbow_delimiters = { highlight = highlight }
require("ibl").setup { scope = { highlight = highlight } }

hooks.register(hooks.type.SCOPE_HIGHLIGHT, hooks.builtin.scope_highlight_from_extmark)
```

### Steps to reproduce

Just edit a file, and sometimes it will do this.

### Expected behavior

<img width="1760" alt="Screenshot 2023-10-06 at 10 50 30" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/90651091/9de2e0de-6b41-4abc-865a-dad85d5b8725">
It looks perfect in lua for example

### Neovim version (nvim -v)

NVIM v0.9.1

**Comment by FormalSnake** [comment] 2023-10-06 09:53
while doing some research I came across a cooler config aswel, but still the same issue.
```lua
vim.api.nvim_set_hl(0, "RainbowRed", { fg = "#E06C75" })
vim.api.nvim_set_hl(0, "RainbowBlue", { fg = "#61AFEF" })
require("ibl").setup { scope = { highlight = { "RainbowRed", "RainbowBlue" } } }
local hooks = require "ibl.hooks"
hooks.register(hooks.type.SCOPE_HIGHLIGHT, function(_, _, scope, _)
	if scope:type() == "if_statement" then
		return 2
	end
	return 1
end)

```

**Comment by FormalSnake** [comment] 2023-10-06 11:46
So I noticed that this is caused by the gap to be extremely wide, but why is this a thing though

**Comment by lukas-reineke** [comment] 2023-10-06 14:18
Duplicate of #665

**Closed by lukas-reineke** 2023-10-06 14:18 UTC
Labels: bug
