### ISSUE TITLE
listchar: trailing comma error

### ISSUE THREAD

**Issue by DerWeh** [lukas-reineke/indent-blankline.nvim#189] opened 2021-08-30 14:49 UTC
If listchar contains a trailing comma, e.g.
```vim
set listchars=tab:│\ ,nbsp:␣,trail:•,extends:⟩,precedes:⟨,
```
the plugin crashes with the error:

```
Error detected while processing /home/andreasw/.config/nvim/plugged/indent-blankline.nvim/plugin/indent_blankline.vim:
line   27:
E5108: Error executing lua vim/shared.lua:423: s: expected string, got nil
stack traceback:
        vim/shared.lua:423: in function 'trim'
        ...ount_nvimLCholV/usr/share/nvim/runtime/lua/vim/_meta.lua:497: in function 'get'
        ...gged/indent-blankline.nvim/lua/indent_blankline/init.lua:32: in function 'setup'
        [string ":lua"]:1: in main chunk
```
I don't know if a trailing comma is discouraged in `Vim`. Had it in my `init.vim` for ages, this was the first time I ran into trouble.

**Comment by lukas-reineke** [comment] 2021-08-31 00:57
this is a duplicate of #162

**Closed by lukas-reineke** 2021-08-31 00:57 UTC
