### ISSUE TITLE
changes cursor color to background color when on indented spaces

### ISSUE THREAD

**Issue by lukasvrenner** [lukas-reineke/indent-blankline.nvim#551] opened 2023-03-13 21:16 UTC
When I activate this, it changes to cursor color the same color as my neovim background. This is only the case when the cursor is over an empty space that contains indents. I apologize for not having a screenshot/recording; I haven't gotten that set up yet.

**Comment by lukas-reineke** [comment] 2023-03-23 04:46
Duplicate of #346

**Closed by lukas-reineke** 2023-03-23 04:46 UTC
