### ISSUE TITLE
How to make Visual highlight and linehl highlight overwrite the indents?

### ISSUE THREAD

**Issue by KritPaoIn** [lukas-reineke/indent-blankline.nvim#552] opened 2023-03-20 14:06 UTC
config:
```lua
require("indent_blankline").setup({
    char = "▏",
    context_char = "▏",
    char_highlight_list = {
        "IndentBlanklineIndent1",
        "IndentBlanklineIndent2",
        "IndentBlanklineIndent3",
        "IndentBlanklineIndent4",
    },
    space_char_highlight_list = {
        "IndentBlanklineIndent1",
        "IndentBlanklineIndent2",
        "IndentBlanklineIndent3",
        "IndentBlanklineIndent4",
    },
    show_trailing_blankline_indent = false,
})
```

<img width="815" alt="Screenshot 2023-03-20 at 8 59 36 PM" src="https://user-images.githubusercontent.com/92923965/226362754-7eb1acfe-1584-4cad-92ab-c7ca79c3a1b4.png">
<img width="812" alt="Screenshot 2023-03-20 at 8 59 48 PM" src="https://user-images.githubusercontent.com/92923965/226362817-5247a7bd-d58f-4c9c-9d11-bb8627ac5f41.png">

**Comment by lukas-reineke** [comment] 2023-03-23 04:48
Duplicate of #132

**Closed by lukas-reineke** 2023-03-23 04:48 UTC
