### ISSUE TITLE
Bad indentation of scope for multi-line function definition

### ISSUE THREAD

**Issue by sfc-gh-mjendruk** [lukas-reineke/indent-blankline.nvim#752] opened 2023-10-23 14:23 UTC
### Problem

I noticed an indentation issue of the scope highlighting when viewing C++ files. However I saw the same issue also in Java files so I assume it's a general issue.

My project puts the opening brace `{` in the same line as the if-clause, function parameters, etc. If the parameter list spans multiple lines then it uses the wrong indentation to display the scope (see images).

<img width="373" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/64833375/cd0faf7f-7965-49dd-90ba-64e4f76b34cb">

<img width="248" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/64833375/141e237f-c8a1-4470-8193-2086f35e2765">

### Steps to reproduce

* This is using indent-blankline v3.
* Scopes must be enabled.
* Create a C++ file and a function with a multi-line parameter list as shown in the images.
* Move the cursor inside the function

### Expected behavior

It should instead highlight the leftmost line in case of the function scope and in case of the if-clause, it should highlight the 2nd line, aligning with the indentation of the `if`.

### Neovim version (nvim -v)

0.9.1

**Comment by Danielkonge** [comment] 2023-10-23 23:09
If you want to keep the meaning of scope, I don't think it should just highlight the first line in the first picture or the second line in the second picture (assuming the scope is within the curly braces?). I guess you would want it to highlight lines 216-219 in the first picture and all but the top row of the second line in the second picture. I don't think this would look very good though. 

I think your formatting style just doesn't really work well together with scope, and it might be better to just use current indent for those files when it is ready.

**Comment by lukas-reineke** [comment] 2023-10-24 01:05
Yeah, your formatting is just very weird. The scope is correct, it starts with the curly braces. It just doesn't look correct because of your formatting.

There isn't really anything I can do.

**Comment by sfc-gh-mjendruk** [comment] 2023-10-24 09:39
Hello, thank you for your responses.

I attached two more images that visualize in red how where I think the scope highlighting should be placed. You're right that the scope is identified correctly, it is just the placement which is not ideal.

<img width="373" alt="277366300-cd0faf7f-7965-49dd-90ba-64e4f76b34cb" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/64833375/2b1f2faf-d538-4c94-80e8-0fb234d21cef">
<img width="248" alt="277368726-141e237f-c8a1-4470-8193-2086f35e2765" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/64833375/06bd3416-269a-4dba-9ac0-d8e3db93cafa">

The code formatting actually doesn't really matter as along as the function parameters are placed on separate lines, which is really really common for functions with long parameter names if you want to adhere to any kind of maximum line length. In the example this is of course not really necessary because the parameter types are short. Putting the opening brace on the same line is also really common in C++, Java, and probably other languages too. Nothing weird about that.

Here is a different parameter formatting which shows the same issue:
<img width="296" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/64833375/e4bdcb8f-13de-4833-b438-32f88b986ed9">

Here is where I think it should be placed.
<img width="296" alt="277614435-e4bdcb8f-13de-4833-b438-32f88b986ed9" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/64833375/c46b1ac2-b973-457f-8bd8-d69f970d25fe">

Here is a Java example showing the same issue:

<img width="390" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/64833375/c0ab9811-4f57-4616-8b68-4e521a008f8c">

To me it looks like the scope indentation is simply based on the line of the opening brace. My idea for a possible fix would be to determine the indentation based on the closing brace instead? This could be configured using an additional option. I think this would work for most C-like languages and formatting styles.

**Comment by lukas-reineke** [comment] 2023-10-24 10:06
Fair, basing the scope indent on the end of the scope would make this look better.

But the way the scope is currently implemented, this is not possible. It would require a lot of refactoring.	
I don't think I will work on this, PRs are always welcome.

**Comment by Danielkonge** [comment] 2023-11-09 14:20
I have run into what seems to be the same problem. It seems that the problem is caused by the newline in the function or if statement (+ the way the C language tree works). Here are some pictures showing how different formatting doesn't give the problem, but a newline in the if statement and `{` at the end of the line doesn't work.

<img width="322" alt="Screenshot 2023-11-08 at 16 57 23" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/6d9b7d32-a69f-4147-bfde-5ac59bdb6d17">
<img width="223" alt="Screenshot 2023-11-08 at 16 54 25" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/68b15a44-f1e7-4403-ab31-cbd348451f2a">
<img width="210" alt="Screenshot 2023-11-08 at 16 57 07" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/7075380/122b900e-8a67-4e84-95b9-54e88443b799">

I think I have an idea for how to solve this after #743 is committed, so I can look at it at that time.

**Comment by Danielkonge** [comment] 2023-12-15 12:45
@sfc-gh-mjendruk #795 fixes this for my test cases (above pictures). Could you check if it highlights as you wanted too? (I think the red line goes up one more line than your pictures, because it starts highlighting on the line with `{` which is what starts the scope [this can be seen by showing the exact scope start].)

**Closed** 2023-12-21 03:03 UTC
Labels: bug

**Comment by sfc-gh-mjendruk** [comment] 2023-12-21 15:54
Hello, thanks for your work. It got a little better, but it's still not entirely as I would expect it:

There is now no visible scope line in the following case. Previously, the scope line would be aligned with `int var3) {`

<img width="385" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/64833375/1d740147-5272-4989-9fc7-33da6df8c6a2">

If I add something whose indentation level is higher than `int var3) {` then the scope line appears.

<img width="424" alt="image" src="https://github.com/lukas-reineke/indent-blankline.nvim/assets/64833375/c5bba819-1728-4e0b-b6cf-bcab2fc80f3d">

**Comment by sfc-gh-mjendruk** [comment] 2024-01-02 12:20
Hi, I tried out v3.5.1 again, and now it looks like in your screenshot. Not sure what was wrong before, thank you!
