### ISSUE TITLE
Indent guides aren't redrawn after reducing all folds

### ISSUE THREAD

**Issue by maciejzj** [lukas-reineke/indent-blankline.nvim#546] opened 2023-03-05 09:49 UTC
When I fold the whole file with `zM` and unfold it with `zR` the guides are not redrawn, as in the gif below:

![nvim-blank](https://user-images.githubusercontent.com/20227552/222953041-07c9f422-67fc-44c3-b9f3-87424b30139c.gif)

Plugin version: Version 2.20.4 (18bd04d80c9a73d399c1061fa0c3b14a7614399)
Neovim version: NVIM v0.8.3
Neovim config: https://github.com/maciejzj/dotfiles/blob/master/init.lua

**Comment by lukas-reineke** [comment] 2023-03-23 04:24
Duplicate of #449
This is a limitation of Neovim, nothing I can do about it.

**Closed by lukas-reineke** 2023-03-23 04:24 UTC

**Comment by maciejzj** [comment] 2023-03-25 09:23
Thanks, sorry to be yet another person to duplicate this.
