### ISSUE TITLE
rendering bug - extra indent marking "comes and goes"

### ISSUE THREAD

**Issue by EdmundsEcho** [lukas-reineke/indent-blankline.nvim#900] opened 2024-06-23 16:28 UTC
### Problem

When I move the cursor up and down the file, an extra indentation marker (vertical line) comes and goes.  I have attached an screencast that demonstrates the behavior.  Feel free to ask me more specifics to help troubleshoot the issue. 

https://github.com/lukas-reineke/indent-blankline.nvim/assets/11245417/2d739879-f44a-46fd-8039-5207857976d2

### Steps to reproduce

There is an interaction with other plugins that is causing the issue.  I say that because if I use a min config only using `indent-blankline` the problem goes away. 

I suspect it might be `lspsaga.lua` when it renders the "breadcrumbs" that depend on where the cursor is in relation to the nested code.  That said, re-installing all of the plugins also got rid of the bug.  

All in all, I'm reporting the issue here as more of an FYI to keep an eye on opportunities to filter the trigger for rendering an indentation marker.

### Expected behavior

The extra rendered marker should not ever render. 

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713773202

**Comment by lukas-reineke** [comment] 2024-06-24 01:16
Duplicate of #861
Set your `shiftwidth` correctly and it should go away.

**Closed by lukas-reineke** 2024-06-24 01:16 UTC
Labels: bug

**Comment by EdmundsEcho** [comment] 2024-07-06 14:07
Quick follow-up,

There are a couple of places to set shiftwidth: using the ftp settings, or globally in my init where I set the baseline settings?

To confirm the source of the issue, is it a matter of checking for the setting in the current buffer?  I ask because clearly I have a shiftwidth of 4, but sometimes renders as 2.

Any clarification would be great.
