### ISSUE TITLE
Update Neovim and if not space in line not work

### ISSUE THREAD

**Issue by sphynx79** [lukas-reineke/indent-blankline.nvim#83] opened 2021-04-03 13:33 UTC
Yesterday i updated my Neovim:
```
NVIM v0.5.0-dev+1211-g6db3ba9df
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compilato da runneradmin@fv-az152-77

```
I use lua version, and now i have this Issues, if i insert in blackline une space work nice??

![image](https://user-images.githubusercontent.com/5004160/113479877-b69f6400-9491-11eb-8580-1ac6e9efd475.png)

This is my setting
```
        let g:indent_blankline_enabled = v:true
        let g:indent_blankline_filetype_exclude = ['help', 'nerdtree', 'vista']
        let g:indent_blankline_buftype_exclude = ['terminal']
        let g:indent_blankline_char = '│'
        let g:indent_blankline_char_highlight = 'indentline'
        let g:indent_blankline_show_first_indent_level = v:false
```

**Comment by lukas-reineke** [comment] 2021-04-03 15:02
I can't reproduce this.
Can you make a minimal `init.vim` file to trigger the issue?

**Comment by sphynx79** [comment] 2021-04-03 21:17
I try also with minimal init.vim
```
filetype indent on
filetype plugin on 
syntax enable
set foldmethod=syntax
call plug#begin($HOME.'/vimfiles/plugged')
 Plug 'lukas-reineke/indent-blankline.nvim', { 'branch': 'lua' }
call plug#end()
colorscheme default
```
same problem

![image](https://user-images.githubusercontent.com/5004160/113491639-a78cd600-94d2-11eb-9b37-69f2d2a64dcf.png)

**Comment by lukas-reineke** [comment] 2021-04-04 04:02
I can reproduce :+1: 

This is the same issue as #59. It is a bug in Neovim, there is an issue in Neovim here https://github.com/neovim/neovim/issues/14209

For now, you can fix it by setting `set colorcolumn=99999` (9999 in case you don't want to see it, any value should work)


Thank you for the issue. I'll close this one and keep #59. If you have more questions you can ask there

**Closed by lukas-reineke** 2021-04-04 04:02 UTC
