### ISSUE TITLE
v3 fails to highlight when `set list`

### ISSUE THREAD

**Issue by hinell** [lukas-reineke/indent-blankline.nvim#681] opened 2023-10-03 08:31 UTC
### Problem

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/8136158/c4140c1a-c347-44cb-a05c-28a72dfedc83 "hinell config")
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/8136158/b2224e5c-2bd6-470c-96a8-c0caf4d31b02 "Minimal config") 

[Minimal-reproduction-template](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template#minimal-config).

Above you can see that:
* `<tab>` are ARE NOT higlighted
* `<space>` chars are higlighted

Everything while `set list`
You can disable 

### Steps to reproduce

1. Replicate [Minimal-reproduction-template](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Minimal-reproduction-template#minimal-config)
2. Config:
`./init.lua`
```lua
require("ibl").setup()
```
```vim
" in vim cmdline
set list
```

Try to

```vim
set nolist
```

To see difference.

### Expected behavior

n/a

### Neovim version (nvim -v)

NVIM v0.10.0-dev-ac1c23442f

**Comment by lukas-reineke** [comment] 2023-10-03 09:23
duplicate of #665

**Closed by lukas-reineke** 2023-10-03 09:23 UTC
Labels: bug

**Comment by hinell** [comment] 2023-10-03 13:28
Sorry. Feel free to delete. Thanks.

**Comment by hinell** [comment] 2023-10-03 15:11
@lukas-reineke Please, update [wiki](https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3) or open it for editing. This is a subtle issue and should be covered.
