### ISSUE TITLE
Scrolling horizontally and coming back hides indent lines

### ISSUE THREAD

**Issue by UtkarshVerma** [lukas-reineke/indent-blankline.nvim#531] opened 2023-01-23 02:05 UTC
If l scroll horizontally and come back, then the indent lines are hidden for the viewable area. I think this video will cover it better.

https://user-images.githubusercontent.com/31820255/213954661-cb5d2ea0-c0af-4968-b7e5-fda90da2cfc8.mp4

**Comment by UtkarshVerma** [comment] 2023-01-23 02:15
Just want to add that if I use `nvim-ufo` and have `char_priority = 30` for `indent-blankline`, then I get the expected behaviour. The video above is with `nvim-ufo`.

**Comment by lukas-reineke** [comment] 2023-01-23 03:14
duplicate of https://github.com/lukas-reineke/indent-blankline.nvim/issues/489

**Closed by lukas-reineke** 2023-01-23 03:14 UTC
