### ISSUE TITLE
[bug] indent characters arent shown with folds unless refreshed

### ISSUE THREAD

**Issue by qube-03** [lukas-reineke/indent-blankline.nvim#605] opened 2023-08-20 13:06 UTC
hi!
ive noticed that with indent blankline, whenever using folds in nvim, the indent chars arent shown like this:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/92535344/4484ddf5-2c32-421a-af73-0b7844403415)

this is pretty annoying because visualizing indents is a great help yet it doesnt work when using folds

thanks!

**Comment by qube-03** [comment] 2023-08-20 13:08
weirdly enough, it seems to work for some folds, but not for others:
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/92535344/61d3ec94-d2a6-4bf6-a9e1-9b9ae5c31822)
![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/92535344/986a6d10-7624-432a-bb3e-d1092f806f6e)

these images were taken in the same file

maybe it has to do with multiple fold levels?

**Comment by lukas-reineke** [comment] 2023-08-21 01:27
Duplicate of #265
It's a limitation of Neovim.

It'll be handled a bit nicer in v3 hopefully, but it's not going to be perfect until there are changes upstream.

**Closed by lukas-reineke** 2023-08-21 01:27 UTC

**Comment by qube-03** [comment] 2023-08-21 03:51
oh i see, thanks for the clarification!
