### ISSUE TITLE
Tab characters not shown correctly when `list` is on and `listchars` has `tab`

### ISSUE THREAD

**Issue by loqusion** [lukas-reineke/indent-blankline.nvim#675] opened 2023-10-02 07:21 UTC
### Problem

Default `listchars` is `tab:> ,trail:-,nbsp:+`. When `list` is turned on, tabs are displayed as `>` when they should be treated similarly to `space` in expected behavior below.

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/38332081/12dcdcfa-5850-44fa-a8e3-1b7120c70fa3)

### Steps to reproduce

```lua
local lazypath = "/tmp/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
vim.opt.termguicolors = true

-------------------
vim.opt.list = true
-------------------

require("lazy").setup({
  {
    "lukas-reineke/indent-blankline.nvim",
    config = function()
      require("ibl").setup({})
    end,
  },
  -- uncomment this if the problem is related to scope
  -- {
  --     "nvim-treesitter/nvim-treesitter",
  --     build = ":TSUpdate",
  --     config = function()
  --         require("nvim-treesitter.configs").setup {
  --             ensure_installed = { "rust" }, -- change this to the language you use
  --         }
  --     end,
  -- },
}, { root = "/tmp/lazy" })
```

### Expected behavior

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/38332081/15ecab14-8b08-45bc-b0fb-314180189196)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1261+g09a17f91d0

**Comment by lukas-reineke** [comment] 2023-10-02 08:05
duplicate of #665

**Closed by lukas-reineke** 2023-10-02 08:05 UTC
Labels: bug
