### ISSUE TITLE
Undesired indent lines started to show in dashboard

### ISSUE THREAD

**Issue by ema2159** [lukas-reineke/indent-blankline.nvim#568] opened 2023-04-30 09:04 UTC
Hello. A couple of commits ago the dashboard displayed by [dashboard.nvim](https://github.com/nvimdev/dashboard-nvim) worked just fine, but at some point some undesired indent lines like the ones shown below started to show up. Any idea why that might be?
![image](https://user-images.githubusercontent.com/17773218/235344895-dd965df4-2bea-4b3c-a933-677f03ba8e11.png)

**Comment by lukas-reineke** [comment] 2023-05-01 01:54
Duplicate of #566

**Closed** 2023-05-01 01:54 UTC
