### ISSUE TITLE
Fail to run config when start up

### ISSUE THREAD

**Issue by AhJi26** [lukas-reineke/indent-blankline.nvim#876] opened 2024-05-17 15:59 UTC
### Problem

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/93467279/73c876b2-fd22-441f-a7f1-fcbec890aec5)

### Steps to reproduce

update this plugin use astronvim and nvim 0.12.2

### Expected behavior

Please fix. It is really annoying to have a error every time open nvim.

### Neovim version (nvim -v)

0.12.2

**Comment by sfc-gh-mjendruk** [comment] 2024-05-17 16:22
Hello, I'm getting the same error on 0.9.5.

**Comment by leandrofmoraes** [comment] 2024-05-17 16:29
A temporary solution is to downgrade to a previous version. 
```
{
     'lukas-reineke/indent-blankline.nvim',
     main = 'ibl',
     commit = "3d08501caef2329aba5121b753e903904088f7e6", -- release v3.5.4
     dependencies = 'nvim-treesitter/nvim-treesitter',
     .....
}
```

**Comment by manuelcattelan** [comment] 2024-05-17 16:43
You should simply update Neovim to the lastest stable version, `v0.10.0` (tested).

**Comment by lukas-reineke** [comment] 2024-05-17 16:44
Duplicate of #869

**Closed by lukas-reineke** 2024-05-17 16:44 UTC
Labels: bug

**Comment by lukas-reineke** [comment] 2024-05-17 17:06
> Bro I'm on nvim 0.12.2

You are not, unless you are writing this from the future.
Neovim stable is 0.10, and nightly is 0.11. Either of those will work.
0.12 does not exist yet.
