### ISSUE TITLE
Latest Neovim causes some strange highlights

### ISSUE THREAD

**Issue by kristijanhusak** [lukas-reineke/indent-blankline.nvim#370] opened 2022-03-07 12:46 UTC
Hi,

today I updated Neovim to the latest master, and I started getting strange highlights on the indents.

On this commit everything worked fine https://github.com/neovim/neovim/commit/3230b314862e50899d68b3944134cbffaa797cde:

![before](https://i.imgur.com/AUDL4QX.png)

And this is how it looks with latest master:

![after](https://i.imgur.com/5PC7R9F.png)

**Comment by ChrisAmelia** [comment] 2022-03-07 15:34
I haven't been able to set a full reproduction step yet, but these settings seem to be required for the above bug:

``lua
opt.cursorline  = true
opt.relativenumber = true
```

**Comment by kristijanhusak** [comment] 2022-03-07 15:42
> I haven't been able to set a full reproduction step yet, but these settings seem to be required for the above bug:
> 
> ```lua
> local opt = vim.opt
> opt.cursorline  = true
> opt.relativenumber = true
> ```

You are correct. I have both of these. It seems that `cursorline` is causing this issue, since having `relativenumber` enabled doesn't cause the issue.

**Comment by rawhat** [comment] 2022-03-07 18:20
There might also be a separate issue, I'm not totally sure, but I think this is related/possibly the cause:  https://github.com/neovim/neovim/issues/17638

**Comment by lukas-reineke** [comment] 2022-03-08 01:24
It's the same issue
There is also a discussion here https://github.com/lukas-reineke/indent-blankline.nvim/discussions/368

**Comment by lukas-reineke** [comment] 2022-03-10 01:36
Fixed in the latest version of Neovim
Thank you for investigating

**Closed by lukas-reineke** 2022-03-10 01:36 UTC
