### ISSUE TITLE
Enabling the plugin resets the colorscheme of listchars

### ISSUE THREAD

**Issue by kioplato** [lukas-reineke/indent-blankline.nvim#562] opened 2023-04-19 23:51 UTC
Hello. It seems that every time I enable this plugin, it resets the color scheme.

### Without the plugin:

![Screenshot from 2023-04-20 02-30-19](https://user-images.githubusercontent.com/13189727/233222321-353c529f-5888-4014-82c7-75b405cb0704.png)

### With the plugin:

![Screenshot from 2023-04-20 02-29-55](https://user-images.githubusercontent.com/13189727/233222460-60d65ca5-d7e9-40b4-b656-5cfee4de9c73.png)

### Same thing happens in packer:

![Screenshot from 2023-04-20 02-28-51](https://user-images.githubusercontent.com/13189727/233222540-3266488e-0ee5-4f49-9b53-accd3e03879c.png)

The `plugin-configs/material` file contains `vim.cmd('colorscheme material')`. 
That's my complete configuration. The same thing does not happen with [classic gruvbox](https://github.com/morhetz/gruvbox). Something is going on with the combination of (`material.nvim` or `gruvbox.nvim`) and `indent-blankline`. Both of these trigger the blue listchars. I use `neovim 9.0`.

I can create a MWE and upload the file as a gist if you wish.

**Comment by lukas-reineke** [comment] 2023-04-20 01:59
Looks like a duplicate of #514
It seems to be an issue with loading order, but I haven't had time to properly debug this.


I'll close this ticket, if you want to continue the discussion please do it in #514

**Closed by lukas-reineke** 2023-04-20 01:59 UTC
