### ISSUE TITLE
`context_char` does not fall back to `char` in lua setupj

### ISSUE THREAD

**Issue by goolord** [lukas-reineke/indent-blankline.nvim#545] opened 2023-03-02 17:56 UTC
this setup

```lua
            require("indent_blankline").setup {
                show_end_of_line = true,
                show_current_context = true,
                show_first_indent_level = false,
                show_trailing_blankline_indent = false,
                char = '▏',
            }
```

displays the default `char` for `context_char` instead of the defined `▏`

**Comment by lukas-reineke** [comment] 2023-03-03 00:59
might be a duplicate of #542?

**Comment by goolord** [comment] 2023-03-04 23:46
ah yeah, the title of that is a little weird

**Closed** 2023-03-04 23:47 UTC
